version: '3.7'
services:

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    image: conmodus_frontend:prod
    networks:
      - net_a
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      API_GATEWAY: http://api-gateway
      API_GATEWAY_CLIENT: /api-gateway
      GRAPHQL_ENDPOINT: http://api-gateway/graphql
      GRAPHQL_ENDPOINT_CLIENT: /api-gateway/graphql

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.prod
    image: conmodus_api_gateway:prod
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./services/api-gateway/src:/app/src

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - net_a
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/data:/data

networks:
  net_a:
