version: '3.7'
services:

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX-}_frontend:prod-nossr
    networks:
      - net_a
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      API_ENDPOINT: http://api-gateway/api
      API_ENDPOINT_CLIENT: /api-gateway/api
      GRAPHQL_ENDPOINT: http://api-gateway/graphql
      GRAPHQL_ENDPOINT_CLIENT: /api-gateway/graphql
      CONMODUS_MODE: nossr
      VERSION: ${VERSION-}
    command: npm run prod:nossr

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX-}_api_gateway:prod-nossr
    networks:
      - net_a
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      GRAPHQL_ENDPOINT: /graphql
      API_ENDPOINT: /api
      VERSION: ${VERSION-}
    command: npm run prod

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX-}_nginx:local
    ports:
      - "${PORT_LOCAL}:80"
    networks:
      - net_a

networks:
  net_a:
