version: '3.7'
services:

  conmodus_devssr:
    build:
      context: .
      dockerfile: Dockerfile.devssr
    ports:
      - "80:80"
      - "4001:4001"
    networks:
      - conmodus
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./src:/app/src

networks:
  conmodus: