# DEV environment.
# SSR frontend rendering.
# ALL variables are available in this and the .env file.
version: '3.7'
services:

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX:-}_frontend:devssr
    ports:
      - "4001:4001"
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      API_ENDPOINT: http://api-gateway/api
      API_ENDPOINT_CLIENT: /api-gateway/api
      GRAPHQL_ENDPOINT: http://api-gateway/graphql
      GRAPHQL_ENDPOINT_CLIENT: /api-gateway/graphql
      CONMODUS_BUNDLES_PORT: 4001
      CONMODUS_TIMEOUT: 1000
      CONMODUS_MAX_RENDERS: 10
      CONMODUS_REACT_ROOT: react-root
      CONMODUS_MODE: ssr
      VERSION: ${VERSION:-}
    volumes:
      - ./services/frontend/src:/app/src
      - ./services/frontend/webpack.dev-ssr.js:/app/webpack.dev-ssr.js
      - ./services/frontend/package.json:/app/package.json
    command: npm run dev:ssr

  cms:
    build:
      context: ./services/cms
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX:-}_cms:dev
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      API_ENDPOINT_CLIENT: /api-gateway/api
      GRAPHQL_ENDPOINT_CLIENT: /api-gateway/graphql
      VERSION: ${VERSION:-}
    volumes:
      - ./services/cms/src:/app/src
      - ./services/cms/webpack.dev.js:/app/webpack.dev.js
      - ./services/cms/package.json:/app/package.json
    command: npm run dev

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX:-}_api_gateway:devssr
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      GRAPHQL_ENDPOINT: /graphql
      API_ENDPOINT: /api
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: 1
      POSTGRES_DB: ${POSTGRES_DB:-}
      VERSION: ${VERSION:-}
    volumes:
      - ./services/api-gateway/src:/app/src
    command: npm run dev

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - net_a
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: 1
      POSTGRES_DB: ${POSTGRES_DB:-}

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: ${IMAGE_PREFIX:-}_nginx:local
    ports:
      - "${PORT_LOCAL}:80"
    depends_on:
      - frontend
      - cms
      - api-gateway
      - postgres
    networks:
      - net_a
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/data:/data

networks:
  net_a:
