version: '3.7'
services:

  frontend_prod:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - net_a
    environment:
      NODE_ENV: production
      LOG_LEVEL: info

networks:
  net_a: