version: '3.7'
services:

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: conmodus_frontend:devssr
    ports:
      - "4001:4001"
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      API_ENDPOINT: http://api-gateway/api
      API_ENDPOINT_CLIENT: /api-gateway/api
      GRAPHQL_ENDPOINT: http://api-gateway/graphql
      GRAPHQL_ENDPOINT_CLIENT: /api-gateway/graphql
      CONMODUS_BUNDLES_PORT: 4001
      CONMODUS_TIMEOUT: 1000
      CONMODUS_MAX_RENDERS: 10
      CONMODUS_REACT_ROOT: react-root
      CONMODUS_MODE: ssr
      VERSION: ${VERSION-}
    volumes:
      - ./services/frontend/src:/app/src
      - ./services/frontend/webpack.dev-ssr.js:/app/webpack.dev-ssr.js
      - ./services/frontend/package.json:/app/package.json
    command: npm run dev:ssr

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    image: conmodus_api_gateway:devssr
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      GRAPHQL_ENDPOINT: /graphql
      API_ENDPOINT: /api
      VERSION: ${VERSION-}
    volumes:
      - ./services/api-gateway/src:/app/src
    command: npm run dev

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: conmodus_nginx:local
    ports:
      - "80:80"
    networks:
      - net_a
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/data:/data

networks:
  net_a:
