version: '3.7'
services:

  frontend_devssr:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.devssr
    ports:
      - "80:80"
      - "4001:4001"
    networks:
      - net_a
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./services/frontend/src:/app/src

networks:
  net_a: