# LIVE environment.
# SSR frontend rendering.
# MOST variables are built into the images.
# Secrets such as
#   POSTGRES_PASSWORD
#   POSTGRES_USER
# must be passed though as env variables during 'docker-compose -up' to 'api-gateway' and 'postgres'
# when using thisfile.
#
# The following env variables are required.
#   IMAGE_PREFIX
#   POSTGRES_PASSWORD
#   POSTGRES_USER
#   POSTGRES_DB
#   PORT_LIVE
#   USERNAME

version: '3.7'
services:

  frontend:
    image: ${USERNAME}/${IMAGE_PREFIX:-}_frontend:latest
    networks:
      - net_a

  cms:
    image: ${USERNAME}/${IMAGE_PREFIX:-}_cms:latest
    networks:
      - net_a

  api-gateway:
    image: ${USERNAME}/${IMAGE_PREFIX:-}_api_gateway:latest
    networks:
      - net_a
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_DB: ${POSTGRES_DB:-}

  postgres:
    image: postgres
    restart: always
    networks:
      - net_a
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_DB: ${POSTGRES_DB:-}

  nginx:
    image: ${USERNAME}/${IMAGE_PREFIX:-}_nginx:latest
    ports:
      - "${PORT_LIVE}:80"
    depends_on:
      - frontend
      - cms
      - api-gateway
      - postgres
    networks:
      - net_a

networks:
  net_a:
