version: '3.7'
services:

  frontend:
    image: insidedocker/${IMAGE_PREFIX-}_frontend:latest
    networks:
      - net_a

  api-gateway:
    image: insidedocker/${IMAGE_PREFIX-}_api_gateway:latest
    networks:
      - net_a

  nginx:
    image: insidedocker/${IMAGE_PREFIX-}_nginx:latest
    ports:
      - "${PORT_LIVE}:80"
    networks:
      - net_a

networks:
  net_a:
