const actionTypes = {
    COUNTER_DECREASE: 'COUNTER_DECREASE',
    COUNTER_FETCH: 'COUNTER_FETCH',
    COUNTER_FETCH_SUCCESS: 'COUNTER_FETCH_SUCCESS',
    COUNTER_FETCH2: 'COUNTER_FETCH2',
    COUNTER_FETCH_SUCCESS2: 'COUNTER_FETCH_SUCCESS2',
};

export default actionTypes;
